name: TDR metadata persistence lambda build release and deploy
on:
  push:
    branches:
      - main
    paths:
      - 'lambdas/tdr-draft-metadata-persistence/**'
      - 'lambdas/tdr-draft-metadata-common/**'
      - 'build.sbt'
      - 'project/**'
  workflow_dispatch:

# Using a shared concurrency group across all workflows
concurrency:
  group: 'tdr-draft-metadata-validator-deploy'
  cancel-in-progress: false

permissions: {}

jobs:
  pre-deploy-persistence:
    permissions: { contents: write, id-token: write }
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_build.yml@2d29c2e83fbaba6554c1e0d8c0b45d2015d610b2 # v0.0.41
    with:
      repo-name: tdr-draft-metadata-validator
      lambda-name: draft-metadata-persistence
      artifact-name: draft-metadata-persistence
      artifact-path: lambdas/tdr-draft-metadata-persistence/target/scala-2.13
      java-version: 21
      build-command: |
        sbt "tdrDraftMetadataPersistence/assembly"
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}

  deploy-persistence:
    needs: pre-deploy-persistence
    runs-on: ubuntu-latest
    permissions: { contents: write, id-token: write }
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Deploy lambda
        run: |
          gh workflow run deploy-lambda.yml --ref "$REF_NAME" \
          -f environment=intg \
          -f to-deploy="$NEXT_VERSION" \
          -f lambda-name=draft-metadata-persistence \
          -f deployment-package=draft-metadata-persistence.jar
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          REF_NAME: ${{ github.ref_name }}
          NEXT_VERSION: ${{ needs.pre-deploy-persistence.outputs.next-version }}
