name: TDR metadata checks lambda build release and deploy
on:
  push:
    branches:
      - main
    paths:
      - 'lambdas/tdr-draft-metadata-checks/**'
      - 'lambdas/tdr-draft-metadata-common/**'
      - 'build.sbt'
      - 'project/**'
  workflow_dispatch:

# Using a shared concurrency group across all workflows
concurrency:
  group: 'tdr-draft-metadata-validator-deploy'
  cancel-in-progress: false

permissions: {}

jobs:
  pre-deploy-checks:
    permissions: { contents: write, id-token: write }
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_build.yml@f318ce8a5d99c08b1235663f97fdb1b35844674e # v0.0.39
    with:
      repo-name: tdr-draft-metadata-validator
      lambda-name: draft-metadata-checks
      artifact-name: draft-metadata-checks
      artifact-path: lambdas/tdr-draft-metadata-checks/target/scala-2.13
      java-version: 21
      build-command: |
        sbt "tdrDraftMetadataChecks/assembly"
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}

  deploy-checks:
    needs: pre-deploy-checks
    runs-on: ubuntu-latest
    permissions: { contents: write, id-token: write }
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Deploy lambda
        run: |
          gh workflow run deploy-lambda.yml --ref "$REF_NAME" \
          -f environment=intg \
          -f to-deploy="$NEXT_VERSION" \
          -f lambda-name=draft-metadata-checks \
          -f deployment-package=draft-metadata-checks.jar
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          REF_NAME: ${{ github.ref_name }}
          NEXT_VERSION: ${{ needs.pre-deploy-checks.outputs.next-version }}
